version: "3.8"

services:
  mongo: 
    image: mongo:4.4
    restart: always
    volumes:
      - /data/db
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - "80:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/